# El método de k-means

In [2]:
import numpy as np

In [3]:
data = np.random.random(90).reshape(30,3) # 30 filas en 3 columnas
data

array([[0.71702865, 0.99447687, 0.6847194 ],
       [0.99248446, 0.13276271, 0.65237503],
       [0.42389644, 0.49125774, 0.27738143],
       [0.37268725, 0.77929202, 0.93978462],
       [0.79401518, 0.46953924, 0.83351431],
       [0.79747694, 0.28565944, 0.80767044],
       [0.43583139, 0.52568688, 0.1414311 ],
       [0.01046896, 0.55722497, 0.46741829],
       [0.5826452 , 0.76779007, 0.82745644],
       [0.22129372, 0.12480781, 0.36113552],
       [0.01075906, 0.93364277, 0.90812914],
       [0.46408158, 0.98754158, 0.03039519],
       [0.20028417, 0.36845786, 0.74518116],
       [0.90867474, 0.66613713, 0.55883478],
       [0.25400687, 0.91153375, 0.03063858],
       [0.52322256, 0.04126511, 0.87373423],
       [0.46779887, 0.20171906, 0.18024032],
       [0.04032468, 0.03835709, 0.70080175],
       [0.51092664, 0.20332807, 0.53120515],
       [0.26609644, 0.78785339, 0.46719089],
       [0.27021338, 0.68165879, 0.13916072],
       [0.97513996, 0.82391788, 0.05144861],
       [0.

In [4]:
c1 = np.random.choice(range(len(data))) # selecciona una fila al azar
c2 = np.random.choice(range(len(data))) # selecciona una fila al azar
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.90867474, 0.66613713, 0.55883478],
       [0.90988383, 0.35857332, 0.96129309]])

In [5]:
from scipy.cluster.vq import vq

In [6]:
# array 1, identifica a que cluster pertenece casa muestra
# array 2, distancias al cada cluster
vq(data, clust_centers)

(array([0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 1, 1, 1, 0, 0]),
 array([0.4004774 , 0.39146349, 0.58720421, 0.66724013, 0.20510094,
        0.20384225, 0.64616788, 0.90939125, 0.43449532, 0.8970034 ,
        0.99990919, 0.76171667, 0.74184482, 0.        , 0.8762424 ,
        0.50779719, 0.74390149, 0.96256287, 0.60683075, 0.66039406,
        0.76419902, 0.53549334, 0.88852201, 0.94962092, 0.33632077,
        0.        , 0.36173052, 0.52371951, 0.79186169, 0.83254148]))

In [7]:
from scipy.cluster.vq import kmeans

In [9]:
# muestra los varicentros del cluster
kmeans(data, clust_centers) # Resultado: un array de 2 cluster y sus centros y suma de los cuadrado de los errores Normalizado

(array([[0.39460496, 0.77166972, 0.46843262],
        [0.51618111, 0.23974861, 0.67989168]]), 0.41875038589056934)

In [10]:
kmeans(data, 2) # K=2

(array([[0.26284191, 0.58852584, 0.38662557],
        [0.68848664, 0.47924445, 0.78687013]]), 0.4046805335202421)