# Aggregations: Min, Max, and Everything in Between

In [2]:
import numpy as np

In [2]:
L = np.random.random(100)
sum(L)

53.45055353018293

### Summing the Values in an Array

In [3]:
np.sum(L)

53.450553530182965

In [4]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

171 ms ± 1.69 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.09 ms ± 83.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Minimum and Maximum

In [5]:
min(big_array), max(big_array)

(1.061115614597874e-06, 0.999999576635497)

In [6]:
np.min(big_array), np.max(big_array)

(1.061115614597874e-06, 0.999999576635497)

### Multidimensional aggregates

In [11]:
M = np.random.random((3, 4))
M

array([[0.79545718, 0.98677556, 0.63812617, 0.31589554],
       [0.87898499, 0.06380531, 0.45375816, 0.70404518],
       [0.74830752, 0.67136626, 0.15152852, 0.00252289]])

In [12]:
M.sum()

6.410573280424626

In [13]:
M.min(axis=0)

array([0.74830752, 0.06380531, 0.15152852, 0.00252289])

In [14]:
M.max(axis=1)

array([0.98677556, 0.87898499, 0.74830752])

    np.sum        np.nansum        Compute sum of elements
    np.prod       np.nanprod       Compute product of elements
    np.mean       np.nanmean       Compute median of elements
    np.std        np.nanstd        Compute standard deviation
    np.var        np.nanvar        Compute variance
    np.min        np.nanmin        Find minimum value
    np.max        np.nanmax        Find maximum value
    np.argmin     np.nanargmin     Find index of minimum value
    np.argmax     np.nanargmax     Find index of maximum value
    np.median     np.nanmedian     Compute median of elements
    np.percentile np.nanpercentile Compute rank-based statistics of elements
    np.any        N/A Evaluate     whether any elements are true
    np.all        N/A Evaluate     whether all elements are true

## Comparison Operators as ufuncs

In [3]:
x = np.array([1, 2, 3, 4, 5])

In [5]:
x < 3 # less than

array([ True,  True, False, False, False])

In [6]:
x > 3 # greater than

array([False, False, False,  True,  True])

In [7]:
x <= 3 # less than or equal

array([ True,  True,  True, False, False])

In [8]:
x >= 3 # greater than or equal

array([False, False,  True,  True,  True])

In [9]:
x != 3 # not equal

array([ True,  True, False,  True,  True])

In [10]:
x == 3 # equal

array([False, False,  True, False, False])

In [11]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])