# Mathematical operations

### 1. Array subtraction

In [6]:
import numpy as np

In [7]:
a = np.array( [11, 12, 13, 14])
b = np.array( [ 1, 2, 3, 4])
c = a - b
c

array([10, 10, 10, 10])

### 2. Squaring an array

In [8]:
b**2

array([ 1,  4,  9, 16], dtype=int32)

### 3. A trigonometric function performed on the array

In [9]:
np.cos(b)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### 4. Conditional operations

In [10]:
b<2

array([ True, False, False, False])

### 5. Matrix multiplication

In [11]:
A1 = np.array([[1, 1],
[0, 1]])

A2 = np.array([[2, 0],
[3, 4]])

A1 * A2

array([[2, 0],
       [0, 4]])

Dot Product: https://en.wikipedia.org/wiki/Dot_product

In [12]:
np.dot(A1, A2)

array([[5, 4],
       [3, 4]])

### 6. Multiplicar array

In [3]:
a = np.arange(5).reshape(1,5)
a += 1
a*a

array([[ 1,  4,  9, 16, 25]])

In [4]:
a = np.arange(5).reshape(1,5) + 1 
b = np.arange(5).reshape(5,1) + 1 
a * b

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

### 7. Concatenar arrays

In [6]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [7]:
z = np.concatenate([x, y, [99, 99, 99]]) 
z

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

### 8. Concatenate two-dimensional arrays 

In [13]:
grid = np.array([[1, 2, 3],[4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [10]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### Arithmetic operators implemented in NumPy

    + np.add Addition                  (e.g., 1 + 1 = 2)
    - np.subtract Subtraction          (e.g., 3 - 2 = 1)
    - np.negative Unary negation       (e.g., -2)
    * np.multiply Multiplication       (e.g., 2 * 3 = 6)
    / np.divide Division               (e.g., 3 / 2 = 1.5)
    // np.floor_divide Floor division  (e.g., 3 // 2 = 1)
    ** np.power Exponentiation         (e.g., 2 ** 3 = 8)
    % np.mod Modulus/remainder         (e.g., 9 % 4 = 1)

In [30]:
x = np.array([1, -2, 3])
np.power(x,2)

array([1, 4, 9], dtype=int32)

#### Absolute value

In [31]:
np.absolute(x)
np.abs(x)

array([1, 2, 3])

#### Trigonometric functions

In [33]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [34]:
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [35]:
x = [-1, 0, 1]
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


### Exponents and logarithms

In [37]:
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [38]:
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [39]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]
