# Creating NumPy Arrays

In [101]:
import numpy as np

In [102]:
np.__version__

'1.14.3'

### 1. Creating NumPy array 

In [103]:
n_array = np.array([
                    [0, 1, 2, 3],
                    [4, 5, 62, 7],
                    [8, 9, 10, 11]
                  ])

print("n_array\n\n",n_array)
print("------------------")
print("n_array",n_array[0])
print("------------------")
print("ndim: ",n_array.ndim)
print("shape: ",n_array.shape)
print("size: ",n_array.size)
print("dtype.name: ",n_array.dtype.name)
print("dtype.nbytes: ",n_array.nbytes)


n_array

 [[ 0  1  2  3]
 [ 4  5 62  7]
 [ 8  9 10 11]]
------------------
n_array [0 1 2 3]
------------------
ndim:  2
shape:  (3, 4)
size:  12
dtype.name:  int32
dtype.nbytes:  48


In [104]:
array_fload = n_array.astype('float32')
array_fload

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5., 62.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [105]:
np.array([ range(i, i + 3) for i in [2, 4, 6] ], dtype='float32') 

array([[2., 3., 4.],
       [4., 5., 6.],
       [6., 7., 8.]], dtype=float32)

## Creating Arrays from Scratch

#### 1. np.zeros

In [106]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [107]:
 np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 2. np.ones

In [58]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [91]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [59]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [96]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [98]:
np.empty(3)

array([2.47032823e-323, 6.36598737e-314, 1.90979621e-313])

#### 3. np.xxxspace

In [92]:
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [93]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [94]:
np.logspace(start=0, stop=1, num=10, base=10.0)

array([ 1.        ,  1.29154967,  1.66810054,  2.15443469,  2.7825594 ,
        3.59381366,  4.64158883,  5.9948425 ,  7.74263683, 10.        ])

#### 4. np.arange

In [73]:
np.arange(0, 20, 3)

array([0. , 0.5, 1. , 1.5, 2. ])

#### 5. np.random.random

In [74]:
np.random.random((3, 3))

array([[0.63489434, 0.74237435, 0.4999647 ],
       [0.31351695, 0.57874465, 0.94958216],
       [0.17259355, 0.71995737, 0.52387347]])

#### 6. np.random.normal

In [75]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.58998176,  1.5984821 , -0.7521779 ],
       [-0.99120673, -0.86059279, -0.66727261],
       [-1.70025408,  0.57186729, -1.46575241]])

In [100]:
np.random.normal(loc=1.0, scale= 3.0, size=(3,3))

array([[ 4.20332539, -1.05976843,  1.04461995],
       [-0.12699769,  0.88532909,  2.10392342],
       [ 0.8658289 ,  0.0928746 , -5.67321081]])

In [95]:
std_gaussian = np.random.normal(size=(3,3))
std_gaussian

array([[ 1.25441407,  1.41910204, -0.74385608],
       [-2.5174371 , -1.50709602,  1.14907613],
       [-1.19357825,  1.14104245,  1.50944508]])

#### 7. np.random.randint, uniform

In [76]:
np.random.randint(0, 10, (3, 3))

array([[9, 9, 0],
       [6, 5, 5],
       [9, 3, 0]])

In [79]:
np.random.uniform(low=0.0, high=1.0, size=(3,3))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## NumPy Standard Data Types

    bool_       Boolean (True or False) stored as a byte
    int_        Default integer type (same as C long; normally either int64 or int32)
    intc        Identical to C int (normally int32 or int64)
    intp        Integer used for indexing (same as C ssize_t; normally either int32 or int64)
    int8        Byte (–128 to 127)
    int16       Integer (–32768 to 32767)
    int32       Integer (–2147483648 to 2147483647)
    int64       Integer (–9223372036854775808 to 9223372036854775807)
    uint8       Unsigned integer (0 to 255)
    uint16      Unsigned integer (0 to 65535)
    uint32      Unsigned integer (0 to 4294967295)
    uint64      Unsigned integer (0 to 18446744073709551615)
    float_      Shorthand for float64
    float16     Half-precision float: sign bit, 5 bits exponent, 10 bits mantissa
    float32     Single-precision float: sign bit, 8 bits exponent, 23 bits mantissa
    float64     Double-precision float: sign bit, 11 bits exponent, 52 bits mantissa
    complex_    Shorthand for complex128
    complex64   Complex number, represented by two 32-bit floats
    complex128  Complex number, represented by two 64-bit floats