# Shape manipulation

In [39]:
import numpy as np
n_array = np.array([
                    [0, 1, 2, 3],
                    [4, 5, 62, 7],
                    [8, 9, 10, 11]
                  ])
n_array

array([[ 0,  1,  2,  3],
       [ 4,  5, 62,  7],
       [ 8,  9, 10, 11]])

### 1. Shape manipulation

In [6]:
n_array.ravel()           # ravel 

array([ 0,  1,  2,  3,  4,  5, 62,  7,  8,  9, 10, 11])

In [7]:
n_array.shape = (6,2)     # shape 
n_array

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [62,  7],
       [ 8,  9],
       [10, 11]])

In [8]:
n_array.transpose()      # transpose

array([[ 0,  2,  4, 62,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

### 2. Resizing arrays 

- Attention because reshape creates just views, not copies

In [9]:
original_array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
Array_a = original_array.reshape(4,2)
Array_a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [13]:
Array_b = original_array.reshape(4,2).copy()
Array_b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [16]:
Array_c = original_array.reshape(2,2,2)
Array_c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### 3. Sub arrays as no-copy views

In [38]:
#Attention because reshape creates just views, not copies
x2_sub = original_array[:4]
x2_sub[0]=-58

print("Sub array: ",x2_sub)
print("Original array:",original_array)

Sub array:  [-58   2   3   4]
Original array: [-58   2   3   4   5   6   7   8]


### 4. Array as copy

In [37]:
x2_sub_copy = original_array[:4].copy()
x2_sub_copy[0] = -33

print("Copy: ",x2_sub_copy)
print("Original array:",original_array)

Copy:  [-33   2   3   4]
Original array: [99  2  3  4  5  6  7  8]


### 5. Splitting of arrays

In [44]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
x1, x2, x3

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))

In [45]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
